### ISSUE TITLE
PWM_Output "class"

### ISSUE THREAD

**Issue by kevinfox-code** [JaredD-SWENG/VDI-ADC-Modular-System#6]
## Description
Implement and test PWM control for Timer 2 on Pin PA5 to achieve a 20% duty cycle.

## Branch Link
Work for this issue is being done in the branch:  
branch: [stm32-pwm-control](https://github.com/JaredD-SWENG/VDI-ADC-Modular-System/tree/stm32-pwm-control)

## Tasks
- [ ] Configure PA5 for PWM output.
- [ ] Set up Timer 2 for 50 Hz frequency.
- [ ] Test duty cycle using an oscilloscope.

/relate subtask-of #5 

- [GPIO Alternate Functions Documentation](https://link.com)
